# Generated by Django 4.2.11 on 2024-04-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_hashtag_post_hastag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='hastag',
            new_name='hashtag',
        ),
    ]
